spring.application.name=identity-service
server.port=8001

spring.datasource.url=jdbc:postgresql://localhost:5432/identity_db
spring.datasource.username=${DB_USERNAME:t3nexus}
spring.datasource.password=${DB_PASSWORD:t3nexus}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

app.kafka.topic.user-registered=oauth2.user.registered
app.kafka.topic.session-issued=oauth2.session.issued
app.kafka.topic.session-revoked=oauth2.session.revoked
app.kafka.topic.dlq=identity-service.dlq
app.kafka.consumer-group=identity-service

# MinIO
app.minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
app.minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
app.minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
app.minio.user-avatars-bucket=user-avatars

# Multipart
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Redis rate limiter
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

#logging.structured.format.console=logstash
management.tracing.sampling.probability=1.0
logging.level.io.micrometer.tracing=DEBUG
logging.level.org.springframework.boot.actuate.autoconfigure.tracing=DEBUG

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8004


