spring.application.name=identity-service
server.port=8001

spring.datasource.url=jdbc:postgresql://localhost:5432/identity_db
spring.datasource.username=${DB_USERNAME:t3nexus}
spring.datasource.password=${DB_PASSWORD:t3nexus}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Redis rate limiter
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

#logging.structured.format.console=logstash
management.tracing.sampling.probability=1.0
logging.level.io.micrometer.tracing=DEBUG
logging.level.org.springframework.boot.actuate.autoconfigure.tracing=DEBUG


