FROM debezium/connect:2.7.3.Final

USER root

RUN curl -fsSL \
        -o /kafka/connect/debezium-connector-postgres/debezium-scripting-2.7.3.Final.jar \
        https://repo1.maven.org/maven2/io/debezium/debezium-scripting/2.7.3.Final/debezium-scripting-2.7.3.Final.jar \
    && curl -fsSL \
        -o /kafka/connect/debezium-connector-postgres/groovy-4.0.21.jar \
        https://repo1.maven.org/maven2/org/apache/groovy/groovy/4.0.21/groovy-4.0.21.jar \
    && curl -fsSL \
        -o /kafka/connect/debezium-connector-postgres/groovy-jsr223-4.0.21.jar \
        https://repo1.maven.org/maven2/org/apache/groovy/groovy-jsr223/4.0.21/groovy-jsr223-4.0.21.jar \
    && curl -fsSL \
        -o /kafka/connect/debezium-connector-postgres/groovy-json-4.0.21.jar \
        https://repo1.maven.org/maven2/org/apache/groovy/groovy-json/4.0.21/groovy-json-4.0.21.jar

USER 1001
