spring.application.name=customer-service
server.port=8002

spring.datasource.url=jdbc:postgresql://localhost:5433/customer_db
spring.datasource.username=${DB_USERNAME:t3nexus}
spring.datasource.password=${DB_PASSWORD:t3nexus}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
app.kafka.topic.customer-account-created=identity.customer-account.created
app.kafka.topic.dlq=customer-service.dlq
app.kafka.consumer-group=customer-service

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#logging.structured.format.console=logstash
management.tracing.sampling.probability=1.0
logging.level.io.micrometer.tracing=DEBUG
logging.level.org.springframework.boot.actuate.autoconfigure.tracing=DEBUG


