spring.datasource.url=jdbc:postgresql://localhost:5438/order_db
spring.datasource.username=t3nexus
spring.datasource.password=t3nexus

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
