spring.application.name=order-service
server.port=8007

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5438/order_db
spring.datasource.username=${DB_USERNAME:t3nexus}
spring.datasource.password=${DB_PASSWORD:t3nexus}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Observability
management.tracing.sampling.probability=1.0
